### ISSUE TITLE
syscall fstat() parameters are not displayed

### ISSUE THREAD

**Issue by alban** [kinvolk/traceloop#12]
fstat has the following prototype:
```
       int fstat(int fd, struct stat *statbuf);
```
However, straceback currently does not show the parameters:
```
fstat() = 0
```

This is because we don't have a entry for `/sys/kernel/debug/tracing/events/syscalls/sys_enter_fstat/`, unlike other syscalls. We should investigate why.

**Comment by pothos** [comment]
Seems they in `sys_enter_newfstatat`, `sys_enter_newfstat`, and `sys_enter_newlstat`.

**Comment by pothos** [comment]
Currently we have these mismatches where `/usr/include/asm/unistd_64.h` has names which do not have a same `debug/tracing/events/syscalls/sys_enter_$NAME` folder:
```
stat
fstat
lstat
sendfile
uname
uselib
_sysctl
umount2
create_module
get_kernel_syms
query_module
nfsservctl
getpmsg
putpmsg
afs_syscall
tuxcall
security
set_thread_area
get_thread_area
epoll_ctl_old
epoll_wait_old
vserver
```
We need to postprocess a bit more.

**Comment by pothos** [comment]
We can at least fix the relation of `_sysctl` and `__sysctl`, the `new*stat` and `*stat` variants, `newuname` and `uname`, and `umount2` and `umount`.
